[package]
name = "joymapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12"
libc = "0.2"
uinput-sys = "0.1"
